site_name: MARS Documentation
site_url: https://mydomain.org/MARSDocs

theme:
  name: material
  features:

    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.tabs.link
    - navigation.footer
  palette:

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode

    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - admonition
  - pymdownx.details

extra_css:
  - styles/style.css

nav:
  - Home: getting-started/overview.md
  - Getting Started: 
    - Creating a project: getting-started/creating-a-project.md
    - Libraries: getting-started/libraries.md
    - APIS: getting-started/apis.md
  - Robot base:
    - Manifest: robotbase/manifest.md
    - Superstructure:
      - Superstructure: robotbase/superstructure/sup.md
      - Superstructure IO: robotbase/superstructure/sup-io.md
      - Superstructure Data: robotbase/superstructure/sup-data.md
    - Bindings: 
      - Controller map: robotbase/bindings/controller-map.md
      - Controller bindings: robotbase/bindings/controller-bindings.md
      - Auto bindings: robotbase/bindings/auto-bindings.md
      - Test bindings: robotbase/bindings/test-bindings.md
    - Key manager: robotbase/keymanager.md
    - Simulation: robotbase/simulation.md
    - Telemetry: robotbase/telemetry.md
  - Mechanisms: 
    - Commands: mechanisms/commands.md
    - Mechanism creation: mechanisms/new-module.md
    - Mechanism file: mechanisms/mechanism.md
    - Mechanism code: mechanisms/code.md
    - Mechanism IO: mechanisms/io.md
    - Mechanism requests: mechanisms/request.md
    - Mechanism request factory: mechanisms/request-factory.md
    - Mechanism IO motor: mechanisms/hardware.md
    - Mechanism simulation: mechanisms/simulation.md
    - Mechanism test: mechanisms/test.md
  - Tools:
    - Alloy: tools/alloy.md
    - Blackboard: tools/blackboard.md
    - Dashboard: tools/dashboard.md
    - Logger: tools/logs.md
    - MARS Terminal: tools/mars-terminal.md
  - Advanced Tools:
    -  Creating libraries: advanced-tools/creating-libraries.md
    - Gathering modules: advanced-tools/gathering-modules.md
    - Nodes: advanced-tools/nodes.md